spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
mybatis:
  configuration:
#    驼峰命名
    map-underscore-to-camel-case: true
logging:
  # 配置日志文件存储位置
  file:
    path: /Users/gwf/IdeaProjects/exam/log
  # 给dao层设置日志输出等级，设为debug后就可以再控制台看到 sql 输出语句
  level:
    cn.nbt.pojo: debug
